-- Create the research_papers table
CREATE TABLE public.research_papers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    summary text,
    content text,
    published_date date
);

-- Insert seed data into the research_papers table
INSERT INTO public.research_papers (title, summary, content, published_date)
VALUES
    ('The Future of On-Premise AI in Enterprise', 'An in-depth analysis of data sovereignty and performance benefits.', 'Full content of the paper on The Future of On-Premise AI in Enterprise. This paper delves into the critical advantages of on-premise AI deployments, focusing on data sovereignty, reduced latency, and enhanced security. It presents a comparative analysis against cloud-based solutions in the context of large-scale enterprise applications.', '2025-07-01'),
    ('Human-AI Collaboration: A New Paradigm', 'Exploring the symbiotic relationship between human and digital employees.', 'Full content of the paper on Human-AI Collaboration. This research explores the evolving dynamics between human and AI workers, proposing a new paradigm where AI acts as a collaborative partner rather than just a tool. It includes case studies on improved productivity and innovation.', '2025-06-01'),
    ('The ''Maestro & Orchestra'' Concept in Practice', 'A case study on managing multiple AI agents from a single interface.', 'Full content of the paper on The ''Maestro & Orchestra'' Concept. This paper provides a practical case study on implementing a centralized management system for a fleet of specialized AI employees. It details the architecture and benefits of the ''Maestro'' controller in orchestrating complex business processes.', '2025-05-01');

-- 3. Enable RLS and create a policy for public read access
ALTER TABLE public.research_papers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for all users" ON public.research_papers
FOR SELECT
USING (true);
